---
- hosts: all
  gather_facts: no
  tasks:
    - name: Install dependencies
      yum:
        state: present
        name:
        - NetworkManager-glib
        - nm-connection-editor
        - libsemanage-python
        - policycoreutils-python
...
