---
- hosts: all
  roles:
    - role: ericsysmin.chrony
      chrony_pkg_state: latest
      chrony_service_state: started
      chrony_service_enabled: yes
      chrony_config_server:
      - dc1.test.local
      - dc2.test.local
...
